using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bulletin.Board.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddListingSlug : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Step 1: extension required for diacritic-stripping during backfill.
            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS unaccent;");

            // Step 2: add the column nullable so we can backfill before enforcing NOT NULL.
            // The autogenerated AddColumn(NOT NULL, default '') would crash the chk_listing_slug_format
            // check constraint immediately for any pre-existing row, so we override it.
            migrationBuilder.AddColumn<string>(
                name: "slug",
                table: "listings",
                type: "character varying(120)",
                maxLength: 120,
                nullable: true);

            // Step 3: backfill slugs from TitleEn (lowercase, unaccented, kebab-case, trimmed to 120).
            migrationBuilder.Sql(@"
                UPDATE listings
                SET slug = NULLIF(
                    trim(both '-' from
                        regexp_replace(
                            regexp_replace(
                                lower(unaccent(""TitleEn"")),
                                '[^a-z0-9]+', '-', 'g'
                            ),
                            '-{2,}', '-', 'g'
                        )
                    ),
                    ''
                )
                WHERE slug IS NULL;
            ");

            // Step 4: rows where TitleEn was empty/symbols-only fall back to 'listing' so the
            // collision-resolution step below assigns them deterministic suffixes.
            migrationBuilder.Sql(@"
                UPDATE listings
                SET slug = 'listing'
                WHERE slug IS NULL OR slug = '';
            ");

            // Step 5: enforce 120-char ceiling on backfilled values BEFORE collision resolution,
            // because long titles can produce >120-char slugs that wouldn't fit the column.
            migrationBuilder.Sql(@"
                UPDATE listings
                SET slug = trim(both '-' from substring(slug from 1 for 120))
                WHERE length(slug) > 120;
            ");

            // Step 6: resolve collisions deterministically by CreatedAt order.
            // Earliest CreatedAt keeps the bare slug; subsequent ones get -2, -3, ...
            // Truncate base when needed so the suffix fits within 120 chars.
            migrationBuilder.Sql(@"
                WITH numbered AS (
                    SELECT ""Id"",
                           slug AS base_slug,
                           ROW_NUMBER() OVER (PARTITION BY slug ORDER BY ""CreatedAt"", ""Id"") AS rn
                    FROM listings
                )
                UPDATE listings l
                SET slug = CASE
                    WHEN n.rn = 1 THEN n.base_slug
                    ELSE
                        trim(both '-' from substring(n.base_slug from 1 for 120 - length('-' || n.rn::text)))
                        || '-' || n.rn::text
                END
                FROM numbered n
                WHERE l.""Id"" = n.""Id"" AND n.rn > 1;
            ");

            // Step 7: lock the column down — NOT NULL.
            migrationBuilder.AlterColumn<string>(
                name: "slug",
                table: "listings",
                type: "character varying(120)",
                maxLength: 120,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(120)",
                oldMaxLength: 120,
                oldNullable: true);

            // Step 8: unique index — public route /listing/detail/{slug} must resolve unambiguously.
            migrationBuilder.CreateIndex(
                name: "idx_listings_slug_unique",
                table: "listings",
                column: "slug",
                unique: true);

            // Step 9: format guard — same regex as SlugGenerator. Defends against direct DB writes.
            migrationBuilder.AddCheckConstraint(
                name: "chk_listing_slug_format",
                table: "listings",
                sql: "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND length(slug) BETWEEN 1 AND 120");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "idx_listings_slug_unique",
                table: "listings");

            migrationBuilder.DropCheckConstraint(
                name: "chk_listing_slug_format",
                table: "listings");

            migrationBuilder.DropColumn(
                name: "slug",
                table: "listings");

            // unaccent extension is left in place — other migrations may depend on it.
        }
    }
}
